[package]
name = "cmsutil"
version = "0.1.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
edition = "2018"

[dependencies]
wincms = { git = "ssh://git@dev1.everyoneprint.com:7999/eopng/wincms.git", branch = "dev" }
structopt = "0.3"
memmap = "0.7"
log = "0.4"
env_logger = "0.7"
