[package]
name = "cmsutil"
version = "0.1.0"
edition = "2021"

[dependencies]
wincms = { git = "https://github.com/ancwrd1/wincms.git", branch = "dev" }
clap = { version = "4", features = ["std", "derive"] }
memmap2 = "0.7"
log = "0.4"
env_logger = "0.10"
